### PR TITLE
Correcting zzz.R, README.md , and repeated successful builds of EnsDbLite and RepDbLite

### PR DESCRIPTION
**Pull request by arcolombo**
Hi.
Here is proof on my end that these builds were correctly made.
root@e94bfb74b849:/RLibraries/EnsDbLite# R CMD INSTALL .
* installing to library '/usr/local/lib/R/site-library'
* installing *source* package 'EnsDbLite' ...
** R
** inst
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded
* DONE (EnsDbLite)

DESCRIPTION  NAMESPACE  R  inst  man
root@e94bfb74b849:/RLibraries/RepDbLite# R CMD INSTALL .
* installing to library '/usr/local/lib/R/site-library'
* installing *source* package 'RepDbLite' ...
** R
** inst
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded
* DONE (RepDbLite)

1)The first significant change is the README.md, this has the license from Artemis, which is not entirely correct.  The LA is an easy change down the line.

2)  the most significant change is the zzz.R that was changed.  the system.file(....) would successfully grab the file path, however RepDbLite or EnsDbLite could not successfully open up the connection without first have setwd(path) added.  I tried this multiple times.  I also left lib.loc=NULL because the default value of NULL corresponds to all libraries currently known. If the default is used, the loaded packages are searched before the libraries.  So it may not be needed (?).  The setwd(path) fixed my problems on my end.  (needs approval)

3)  The DESCRPTION pkg  title needs gsub  editing because  by  definition (https://cran.r-project.org/doc/manuals/R-exts.html#The-DESCRIPTION-file ) Hyphens and multiple dots errors out.  So I trim out and simplify the naming conventions to take the first portion of the pkg name. 

"The mandatory ‘Package’ field gives the name of the package. This should contain only (ASCII) letters, numbers and dot, have at least two characters and start with a letter and not end in a dot. If it needs explaining, this should be done in the ‘Description’ field (and not the ‘Title’ field). "

4) I was messing around with RegEx'ing the email address, but decided against it.  RCF2822 requirements can take pages of reg Ex and well, I'm a novice. and want to study Math, not to be consumed with coding.  So I wave the white flag here.

### CODE REVIEW

**Comment by arcolombo** [comment]
I closed this because the setwd() is not necessary. and wish to add a new parameter for email so it can be edited

**Comment by ttriche** [comment]
so don't merge it?

any time you see a setwd() in my code, it means I was lazy and didn't
properly implement an optional path parameter along with expansion using
the .Platform$file.sep ... there are also examples in the code of where I
should have used basename() or normalizePath() instead of other options...

but on the other hand these are not math problems, they're schlep work :-/


--t

**Comment by arcolombo** [comment]
No There is another way to simplify it. I'll do A pull req today, I tried to add an email parameter. But the command copySubstitute isn't grabbing the pasted author and email with "Anthony Colombo <acol@gmail.com>". Returns author only.  Bio base has a bug , but your method must stay for the moment.

**Comment by ttriche** [comment]
ok


--t

**Pull request closed without merging**
