### PR TITLE
0 Warnings  and 4 notes,  passing

### PR DESCRIPTION
**Pull request by arcolombo**
This PR solves all WARNINGS, passes TRAVIS
- checking Rd \usage sections ... OK
- checking Rd contents ... OK
- checking for unstated dependencies in examples ... OK
- checking contents of ‘data’ directory ... OK
- checking data for non-ASCII characters ... OK
- checking data for ASCII and uncompressed saves ... OK
- checking files in ‘vignettes’ ... OK
- checking examples ... OK
- checking PDF version of manual ... OK
- DONE

Status: 4 NOTEs
See
  ‘/home/arcolombo/Documents/github_repos/TxDbLite.Rcheck/00check.log’
for details.

won't merge until tested further.

### CODE REVIEW

**Comment by ttriche** [comment]
you a baaaaad man, Anthony

--t

**Comment by arcolombo** [comment]
this also incorporates @ttriche  branch :: master

**Comment by arcolombo** [comment]
DESTROY.

**Comment by arcolombo** [comment]
closing this.   missed some selective importing.  will reopen when I get it right.

Sincerely,
C. Hosoi

**Pull request closed without merging**
