### PR TITLE
Devel Branch has the 5 commits required to fix Ramsingh/TxDbLite

### PR DESCRIPTION
**Pull request by arcolombo**
this has the simplified commits for merging.  It contains all the previous pull requests changes, but a much cleaner commit HEAD history.

### CODE REVIEW

**Comment by arcolombo** [comment]
future fixes:

1) The README.md License agreement could be cleaned, it is copied from Artemis.
2) the email parameter uses very basic regEx.  the future fix should simplify and remove the regEx, and use the R package 'sendmailR' to instead ping the user's email.  The user must know the SMTP host information which can be read in from input.  For now, it is okay to keep a basic stable version for email.  this can be improved in the next pull request.

**Comment by ttriche** [comment]
Merged.  For future reference, anything involving sendmailR and/or internet connectivity is a can of worms that you probably don't want to open :-)

**Comment by arcolombo** [comment]
ok. thank you very much for your comments! currently working on your branch to fix a few things and prepare for this upcoming week,  updates before Thursday.

**Comment by ttriche** [comment]
I pulled TxDbLite post-merge to see if the Drosophila example could run;
since it couldn't, I'm fixing things up so that it can.  Always nice to
demonstrate a specific use case... in other news, Ensembl 82 is coming down
the pipe shortly.


--t

**Comment by arcolombo** [comment]
okay for future references, it should be required (mostly on my end) to show generic builds/run completions across species.  Downloading the Drosophila trnsx.

**Comment by ttriche** [comment]
there are some bugs, I think.  Tested already; the bugs appear to affect
makeEnsDbLitePackage(ensdb, author="Foo Barr <foo@bar.com>")

Will open an issue...


--t

**Comment by arcolombo** [comment]
Yes I saw that in your branch for dev@null.com.   I'm also able to generate the Drosophila errors, the errors occur when squashing the transcripts into the gene base GRanges.  1 sec.  this problem is do-able.

**Comment by arcolombo** [comment]
for Dros,  gxs<-GRanges(...)   class(strand) = list.   which fails because strand must be Rle object,  factor, matrix , or character vector.  maybe just add an if (class(strand)==list) {  set to acceptable object...}

**Comment by ttriche** [comment]
Odd, I do not get that bug

I added the actual FASTA to the package for testing; it is in inst/extdata.  Looks like this will end up being a unit test or vignette type thingy 

--t

**Comment by arcolombo** [comment]
On my end, for Drosophilia_Mal... cdna.all.fa.gz  I produce

 squash <- function(x, by, FUN) { # {{{
    xx <- aggregate(x=x, by=by, FUN=FUN)
    x <- xx[,2]
    names(x) <- xx[,1]
    x
  } # }}}

> x<-xx[,2]
> class(x)
[1] "list"
> 
Here is the gxs<-GRanges (...)  error  with strand as 'list' .
> gxs <- GRanges(seqnames=gxChr,
+                  ranges=IRanges(start=gxStart, end=gxEnd),
+                  strand=gxStrand)
Error in .Call2("Rle_constructor", values, lengths, check, 0L, PACKAGE = "S4Vectors") : 
  Rle of type 'list' is not supported

For human

 x<-xx[,2]
> class(x)
[1] "character"
> 


if I add the 'as.character'  it solves this on my end. now I'm really nervous if you're not generating. ugh.  
 Perhaps we should enforce a character vector in the squash function if one stumbles into this loophole.  

I'm not doing anything fancy, just going line by line, and copying one line at a time using 
ftp://ftp.ensembl.org/pub/release-81/fasta/drosophila_melanogaster/cdna/
 
and class checking everything.

**Comment by arcolombo** [comment]
For the makeEnsDbLite,  the author must be a char vector, and the email  must have <email>  format with email as the new parameter.  author is not copied under maintainer for DESCRIPTION.  in the posted command, there was a missing email param.   (?)

**Comment by arcolombo** [comment]
email = "<some@amil.com>"  must be in this format to R CMD INSTALL  .

**Comment by arcolombo** [comment]
damn it  "\brah some@famli.com \ket "

**Comment by arcolombo** [comment]
My problem with Drosopholia had to do with Rle value not being a correct type.  e.g.

> runValue(Rle(gxStrand))[226]
[1] "c(\"-\", \"+\")"


Note,  I loaded the cdna.all.fa.gz from Ensembl, and tested it on EnsDblLiteFromFasta("Dros...",verbose=TRUE)

your recent commits, perhaps solve this,   on my branch for Dros, I am now required to type check the Rle values.  Not sure how this became corrupted.   this is FYI.

tyvm.

P.S.  if your recent commits were a result of my lack of vision in the commits on my end, please let me know  :)

**Pull request merged**
