### PR TITLE
correcting zzz.R, README.md, without using setwd().  

### PR DESCRIPTION
**Pull request by arcolombo**
The august 27th, 28th  commits are all that I've changed.  It would have been ideal to delete the repo and build over again to remove the long list of commit history.  However, the 27-28 commits are all that are being changed.

 The R CMD check has a few errors that need fixing.
  The NAMESPACE  import(knitr) and depends: knitr were required by CMD check.  The other errors output from CMD check still need a solution;  these commits solve a few of them, and can still be used as a future 'stable' version.

the ensDbLite/zzz.R   and repbdLite/R/zzz.R  were the major if not the only change needed.  The current line of db<-Ens/RepDbLite(system.file("extdata",files[[i]],lib.loc=libname) under the RamsinghLab stable generates "" as an error, which fails to connect to the .sqlite database object required for .onLoad to load and convert the .sqlite object.

1)  the important change of db<-Ens/RepDblite(files[[i]],path)  paths correctly to the library directory and correctly pulls the dir(path) files to load them.  This change was tested and loads all the DbLite libraries generated by makeEns/RepDbLitePkg successfully.

2) The README.md  is also added.  the License agreement is not fully correct, but the bulk of the README.md should go into the future stable version

3)  Most of this commit history shows an investigation of the email parameter under makeEns/RepDbLitePkg(litefile, author,email, version, destDir)  experiment.
  I successfully have a generic RegEx command which checks the email to be under ASCII@ASCII.ASCII  format required and detailed under "Writing R Extensions" manual.
  However, there is an error under BioBase such that when the author = "some character string", and email = "<ASCII@ASCII.ASCII>"  where the symbolic value for MAINTAINER=paste(author,email,sep = " ") is mis-generated.
  the copySubstitute command will not show the paste(author,email,sep="")  string, it will only display author and not the pasted email.     For purposes of production, the stable branch does not need to have BioBase bug investigated.  so the email parameter was decided against.  The commits may be useful if down the line one wishes to debug BioBase copySubstitute arguments.  

here is proof of successfully building for future stable release : 

#RepDbLite -  installs the package output from makeRepDbLitePkg successfully

root@c054484e34ef:/RLibraries/RepDbLite# R CMD INSTALL .
* installing to library '/usr/local/lib/R/site-library'
* installing *source* package 'RepDbLite' ...
** R
** inst
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded
* DONE (RepDbLite)

> sessionInfo()
R version 3.2.2 (2015-08-14)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 14.04.2 LTS

locale:
[1] C

###Loads the data from .onLoad from RepDbLite successfully showing zzz.R works now

####library(RepDbLite) results in data being loaded on auto

> show(RepDbLite.Homo_sapiens.20_07.merged)
RepDbLite :
|package_name: RepDbLite.Homo_sapiens.20_07.merged
|db_type: RepDbLite
|type_of_gene_id: RepBase identifiers
|created_by: TxDbLite 1.9.21
|creation_time: Fri Aug 28 18:22:15 2015
|organism: Hsapiens
|genome_build: RepBase_20_07
|source_file: Homo_sapiens.RepBase.20_07.merged.fa.gz
| 1116 repeat exemplars from 68 repeat families.

####for Ensmbl  installs the output from makeEnsDbLitePkg successfully building the package

root@c054484e34ef:/RLibraries/EnsDbLite# R CMD INSTALL .
* installing to library '/usr/local/lib/R/site-library'
* installing *source* package 'EnsDbLite' ...
** R
** inst
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded
* DONE (EnsDbLite)

#In R, the library and the data is loaded on auto showing the zzz.R is fixed
library(EnsDbLite)
> show(EnsDbLite.Homo_sapiens.81.cdna_mergedWith_ncrna)
EnsDbLite :
|package_name: EnsDbLite.Homo_sapiens.81.cdna_mergedWith_ncrna
|db_type: EnsDbLite
|type_of_gene_id: Ensembl Gene ID
|created_by: TxDbLite 1.9.21
|creation_time: Fri Aug 28 18:33:19 2015
|organism: Hsapiens
|genome_build: 81
|source_file: Homo_sapiens.GRCh38.81.cdna_mergedWith_ncrna.fa.gz
| 212569 transcripts from 62441 bundles (genes).

Despite the long commit history, these commits should be merged into the new stable branch.

Future fixes needed:
 1) README.md license agreement
2) R CMD check

### CODE REVIEW

**Comment by ttriche** [comment]
maybe we should just get rid of the dependence on Biobase and do it
ourselves.  These aren't designed to be works of art, they are designed to
be the simplest thing that could possibly work for the task at hand...


--t

**Comment by arcolombo** [comment]
Let me see if there is a way within  BioBase which  includes a pasted
string, you have to be careful when pasting symbolic values together; it is
not a simple string concatenation. This requires careful thinking IMHO.

  Then email can be a separate parameter requiring type checking.

It would be simpler to find the right method as opposed to throw entire and
entire library.  (more pro's than con's I argue).

If the email parameter is interesting / needed,  then I will spend more
time on it, up to you (?).

**Comment by ttriche** [comment]
personally I don't care if we hardcode it to dev@null.com


--t

**Comment by arcolombo** [comment]
According to "Writing R Extensions" the email must be valid.  This means
that if dev@null.com is not valid, the library may not build.

 As of now, the user must be smart enough to enter the correct info under
author.

**Comment by arcolombo** [comment]
I've tested dev@null.com and it builds.  we can go this route.

**Comment by arcolombo** [comment]
I think we should set MAINTAINER:  "<dev@null.com>"

example

Package: EnsDbLite
Title: Ensembl-based annotation package
Description: Lightweight Ensembl transcript annotations
Version: 1.0
Author: anthony colombo <anthony@gmail.com>
Maintainer:<dev@null.com>
Depends: TxDbLite
Imports: GenomicFeatures, RSQLite
License: Artistic-2.0
organism: Hsapiens
species: Hsapiens
provider: Ensembl
provider_version: 81
release_date: Thu Aug 27 03:08:10 2015
resource_url: ftp://ftp.ensembl.org/pub/release-81
biocViews: AnnotationData, EnsDbLite, Hsapiens


It does build without the author leading the email, this means one can
avoid pasting sym values all together.  I strongly argue that this should
be the new stable.

oot@2baf9f5c937c:/RLibraries/EnsDbLite# R CMD INSTALL .
* installing to library '/usr/local/lib/R/site-library'
* installing *source* package 'EnsDbLite' ...
** R
** inst
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded
* DONE (EnsDbLite)

**Comment by ttriche** [comment]
we could use r-help@r-project.org if we REALLY wanted to be twits ;-)

or set up a circular file on gmail, e.g. TxDbLitePackages@gmail.com


--t

**Comment by ttriche** [comment]
Nobody <dev@null.com>

This will probably not win us a lot of fans but it does satisfy the
criteria...


--t

**Comment by arcolombo** [comment]
One could argue that the base foundation stable should run smoothly and
generically.  extra bells and whistles for first class programming is
considered "downstream".

Let me create a new pull request testing the dummy MAINTAINER.

updates soon.

**Comment by arcolombo** [comment]
i think I found the reason why it's weird.  1 sec.  bugging me too much to
fold this hand so easy.

> system("cat
/usr/local/lib/R/site-library/TxDbLite/repdblite/DESCRIPTION")Package:
@PKGNAME@
Title: @PKGTITLE@
Description: @PKGDESCRIPTION@
Version: @PKGVERSION@

*Author: @AUTHOR@Maintainer: @AUTHOR@*
Depends: TxDbLite
Imports: GenomicFeatures, RSQLite
License: @LIC@
organism: @ORGANISM@
species: @SPECIES@
provider: @PROVIDER@
provider_version: @PROVIDERVERSION@
release_date: @RELEASEDATE@
resource_url: @SOURCEURL@
biocViews: AnnotationData, EnsDbLite, @ORGANISMBIOCVIEW@

**Comment by arcolombo** [comment]
so I've found the mistake.  I'd like to set email as a separate parameter,
and type check it for ASCII@ASCII.ASCII (loosely)

Package: @PKGNAME@
Title: @PKGTITLE@
Description: @PKGDESCRIPTION@
Version: @PKGVERSION@
Author: @AUTHOR@
*Maintainer: @MAINTAINER@*
Depends: TxDbLite
Imports: GenomicFeatures, RSQLite
License: @LIC@
organism: @ORGANISM@
species: @SPECIES@
provider: @PROVIDER@
provider_version: @PROVIDERVERSION@
release_date: @RELEASEDATE@
resource_url: @SOURCEURL@
biocViews: AnnotationData, EnsDbLite, @ORGANISMBIOCVIEW@


On Fri, Aug 28, 2015 at 1:09 PM, Anthony Colombo <anthonycolombo60@gmail.com
> wrote:

> i think I found the reason why it's weird.  1 sec.  bugging me too much to
> fold this hand so easy.
>
> > system("cat
> /usr/local/lib/R/site-library/TxDbLite/repdblite/DESCRIPTION")Package:
> @PKGNAME@
> Title: @PKGTITLE@
> Description: @PKGDESCRIPTION@
> Version: @PKGVERSION@
>
> *Author: @AUTHOR@Maintainer: @AUTHOR@*
> Depends: TxDbLite
> Imports: GenomicFeatures, RSQLite
> License: @LIC@
> organism: @ORGANISM@
> species: @SPECIES@
> provider: @PROVIDER@
> provider_version: @PROVIDERVERSION@
> release_date: @RELEASEDATE@
> resource_url: @SOURCEURL@
> biocViews: AnnotationData, EnsDbLite, @ORGANISMBIOCVIEW@
>
>
> On Fri, Aug 28, 2015 at 12:49 PM, Anthony Colombo <

**Comment by ttriche** [comment]
Ok sounds good

Can you create a separate branch for the pull request with only the commits that you want merged, and I'll merge that?   In an ideal world, I'd also like to have the package automatically installed and submitted to BioC or the AnnotationHub, but we shall see. The latter might deal with the issue of wacky organism specific names and stubs better than the naive approach. 

--t

**Comment by arcolombo** [comment]
the new commits have the MAINTAINER filed properly generated.  the email parameter must be used.
 The new stable branch will check if author is strings only, no email.  if there is an email, it splits the author and assigns entry in split to email object.    it also does very basic regEx of email to ensure that it is ASCII@ASCII.ASCII format (loose check this is very difficult to do actually because international email accounts ... )  . it also checks if email is missing, then assigns TommyTrojan@update.com :)

**Comment by ttriche** [comment]
Re: regex for email:

http://davidcel.is/posts/stop-validating-email-addresses-with-regex/

JWZ has always been a hero of mine.  He was retired by the time I graduated college... I think he was about 27 then. 

--t

**Comment by arcolombo** [comment]
let me simplify the pull into 3-4 commits.  1 sec.

@ JWZ  - this is hilarious.  because it points how inept users are.

**Pull request closed without merging**
