### PR TITLE
Correcting findDupes function, removing Rsamtools function "chrs" from use.

### PR DESCRIPTION
**Pull request by arcolombo**
Hi.  so the findDupes in TxDbLite had errors on my end using Rsamtool's "chrs" funciton which fails if there exist dupes.    so we have to manually detect dupes.

using Biostrings because it is light years faster than seqinr,  we find all duplicated sequences with duplicated sequence names.   The definition of a dupe is any member in the set of duplicates with duplicated sequences and nams.... 

I've tested on   mouse and human ensembl and repbase files.

fastaFiles
[1] "Mus_musculus.GRCm38.83.cdna.all.fa.gz"
[2] "Mus_musculus.GRCm38.83.ncrna.fa.gz"   
> findDupes(fastaFiles=fastaFiles)
found no duplicated sequence names .... no dupes found
named list()
> 

for mouse repBase
fastaFiles
[1] "Mus_musculus.GRCm38.83.cdna.all.fa.gz"
[2] "Mus_musculus.GRCm38.83.ncrna.fa.gz"   
[3] "Mus_musculus.RepBase.20_12.merged.fa" 
> findDupes(fastaFiles=fastaFiles)
there are duplicated sequences: 
$Mus_musculus.RepBase.20_12.merged.fa
[1] "B2_Mm2"  "B2_Mm1t" "B1_Mm"   "BC1_Mm"  "B1_Mus1" "B2_Mm1a"

for human fastaFile list with RepBase

> findDupes(fastaFiles=fastaFiles)
there are duplicated sequences: 
$repeat2.fa
[1] "LTR26B" "SVA_A" 

This seems to work in a general way,  the findDupes funciton returns the list of duplicated sequences that had duplicated names (minor string splitting of "\t" for repbase files and " "  for ensembl files )

then the index kallisto function in artemis can decide to use the in built function  "--make-unique" to auto remove dupes,  or allow the user to pluck out the dupes manually.   

Harold's response is pending regarding how "--make-unique" works, not sure if the dupes are renamed, removed, etc...

looking forward to your review.

Loyally Yours,
Anthony C.

### CODE REVIEW

**Comment by arcolombo** [comment]
The next change that is required that I would like to briefly discuss is  the following:

indexKallisto will now offer a switch control for identifying the default "--make-unique" flag within the function call.   I think we should offer another parameter titled "auto-fix-dupes=TRUE" in the function call indexKalliisto(auto-fix-dupes=TRUE ...)  which would automatically fix the dupes using the "make-unique" given that the findDupes function returns a duplicate.    If the user wants to manually pluck out their dupes, given there exist dupes,  one can turn this parameter to FALSE.

**Comment by ttriche** [comment]
Can't use dashes in an argument due to operator precedence 

--t

**Comment by ttriche** [comment]
if the argument is makeUnique then operators are not an issue.  However I worry that having this be the default may not be a good idea. 

We might want to chat with RepBase about this topic -- I don't see why there need to be identically named, identical sequence entries in two places and I'll bet changing this would benefit all users. 

At that point I think we are good and can then focus on how the inclusion or exclusion of various sequences impacts quantification.  RUV/ERCC integration is a logical place to start, though it may or may not be of interest to any active developers ;-)


--t

**Comment by arcolombo** [comment]
thank you.

The dupes come from merging the Species_rep.ref and Species_sub.fa

I've completed testing scripts that appear to be working in a proper
control flow. maybe a bit rigorous...

essentially,  the concept / problem arises here:
identical sequences is too liberal with calling /identifying a dupe.
Finding identical names is not sufficient because RepBase headers are not
1-1 identical across files (i.e.  all header information includes the
RepBase repeat name, but not all header meta-information is the same across
files).

the pending patch allows for a control flow when indexing a kexp reference
 1) auto pluck the found dupes
2) print the names of the dupe and pluck manually

**Comment by arcolombo** [comment]
yes this could be solved at the RepBase level.  agree we should speak with
them.
 I'm a bit horny to push and publish the first app however.

**Comment by ttriche** [comment]
No such thing as too rigorous
:-D

--t

**Comment by ttriche** [comment]
Either is fine ... I just worry about fallout in downstream analyses if we allow for defaults to paper over fundamental problems. 

--t

**Comment by arcolombo** [comment]
It seems that yes RepBase headers and/or split files is the fundamental
issue.  agree.

**Pull request merged**
